### PR TITLE
Add semi and semi-spacing rules

### PR DESCRIPTION
**Pull request by fredj**
See http://eslint.org/docs/rules/semi and http://eslint.org/docs/rules/semi-spacing

### CODE REVIEW

**Comment by fredj** [comment]
ping @tschaub

**Comment by fredj** [comment]
re-ping @tschaub

**Comment by ahocevar** [comment]
I'm in favour of this change. Other opinions?

**Comment by tschaub** [comment]
Looks good to me.  Please merge.

(And this will be a new major release.)

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
